name: my_smartspace
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  flutter_screenutil: ^0.6.0
  flutter_nfc_reader: ^0.1.0
  #nfc_in_flutter: 2.0.2


  flutter:
    sdk: flutter
  intl: ^0.15.8
  provider: ^3.1.0
  path_provider: ^1.4.0
  flutter_launcher_icons: "^0.7.2"
  json_serializable: ^3.2.3
  flutter_auth_buttons: ^0.6.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^8.0.1



flutter:
  uses-material-design: true
  assets:
    - images/